[project]
name = 'btc-yield-pool'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.btc-yield-pool]
path = 'contracts/btc-yield-pool.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
